### PR TITLE
Added several new sensors and a i2csensors

### PR DESCRIPTION
**Pull request by martindeegan**
Hey I've added 5 new sensors:
bmp180 - Thanks to [MrSpock](https://github.com/MrSpock)
bmp280
lsm303d
l3gd20
lsm9ds0

I've also added `i2csensors` which defines the traits that future sensors implement. This is the same as the sensor traits from rust-i2cdev with the addition of Gyroscope and Magnetometer. I that if the sensors are going to be in separate crates from i2cdev, then the sensor traits should be as well.

Sorry for some of the bad commits, I was getting them onto my Raspberry Pi with git before I switched to scp.

### CODE REVIEW

**Comment by Kixunil** [comment]
Thank you! Note that this crate is mostly WIP and there wasn't wide agreement about moving to it.

I don't think naming the traits crate `i2csensors` is the best idea. I believe it should be called `sensors` or `sensor_traits`, because the sensors don't have to be necessarily implemented using I2C.

BTW, git allows one to edit history and I'm open to editing it in case of commits like "asdf".

**Comment by martindeegan** [comment]
Thats a good point. I noticed that you talked to some of the other imbedded Rust developers about the sensors. Did you come to any conclusion for the future? I am willing to change anything.

I'll look into editing git history to remove those commits.

**Comment by Kixunil** [comment]
Hi, sorry about the delay, I missed it somehow. Thanks for helping! Yes, I was talking with other embedded devs and we didn't reach any conclusion so far. :(

Seems like everyone is busy these days (including myself).

**Comment by Kixunil** [comment]
Thanks guys for your awesome work! I pinged embedded-rust repo, so hopefully this will move forward. I lack free time now but I'll try to help at least a little.

**Pull request closed without merging**
